language: python
python:
  - "2.7"
  - "3.6"
env:
  - SECRET_KEY='nBvb80W09RNCVKJVCVBUIvbvb$hbv&$b_vbvksv'
  - SQLALCHEMY_DATABASE_URI='postgresql://postgres@localhost/bucketlist'
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest